spring:
  datasource:
    url: jdbc:h2:tcp:localhost/~/sequence/todo;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sequence
    password:


  jpa:
    database: h2
    show-sql: true

    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace